/* Generated by bin2c, do not edit manually */
#ifndef __Keyboard_A500_h_included
#define __Keyboard_A500_h_included

/* Contents of file Keyboard_A500.raw */
#define Keyboard_A500_size 128000
extern const unsigned char Keyboard_A500[128000];

#endif    /* __Keyboard_A500_h_included */
